"""
ios/constants.py
================
Defines the final schema columns and default values for the iOS pipeline.
"""

FINAL_COLUMNS = [
    "bundle_id",
    "app_name",
    "description",
    "summary",
    "genreid",
    "content_rating",
    "score",
    "ratings_count",
    "installs",
    "developerid",
    "developer",
    "free",
    "offers_iap",
    "launch_date",
    "days_since_released",
    "months_since_launch",
    "country_code",
    "os_type",
    "default",

    "is_investments",
    "is_crypto",
    "is_finance",
    "is_shopping",
    "is_entertainment",
    "is_social",
    "is_education",
    "is_utility",
    "is_health",
    "is_travel",
    "is_news",
    "is_food_drink",
    "is_lending",
    "is_quick_service",
    "is_ride",

    "is_gaming_action_game",
    "is_real_money_card_and_casino_game",
    "is_word_game",
    "is_trivia_and_puzzle_game",
    "is_strategy_game",
    "is_sports_game",
    "is_simulation_and_role_playing_game",
    "is_racing_game",
    "is_casual_game",
    "is_board_game",
    "is_arcade_game",

    "score_45plus",
    "score_40_45",
    "score_30_40",
    "score_below30",
    "score_missing",

    "installs_10m_plus",
    "installs_1m_10m",
    "installs_100k_1m",
    "installs_below100k",
    "installs_missing",

    "apps_0_3months",
    "apps_3_12months",
    "apps_1_2years",
    "apps_2plus_years",
    "app_age_missing",

    "is_free_app",
    "is_paid_app",

    "offers_iap_flag",
    "no_iap_flag",

    "rating_everyone",
    "rating_teen",
    "rating_mature",
    "rating_everyone10plus",
    "rating_rated3plus",
    "rating_rated7plus",
    "rating_rated12plus",
    "rating_rated16plus",
    "rating_rated18plus",
    "rating_adults18plus",
    "rating_missing",
    "rating_other"
]

CATEGORY_COLS = [
    "is_investments",
    "is_crypto",
    "is_finance",
    "is_shopping",
    "is_entertainment",
    "is_social",
    "is_education",
    "is_utility",
    "is_health",
    "is_travel",
    "is_news",
    "is_food_drink",
    "is_lending",
    "is_quick_service",
    "is_ride",
    "is_gaming_action_game",
    "is_real_money_card_and_casino_game",
    "is_word_game",
    "is_trivia_and_puzzle_game",
    "is_strategy_game",
    "is_sports_game",
    "is_simulation_and_role_playing_game",
    "is_racing_game",
    "is_casual_game",
    "is_board_game",
    "is_arcade_game"
]
